name: Build iOS IPA

on:
  workflow_dispatch:
    inputs:
      spa_zip_base64:
        description: 'Base64 encoded SPA ZIP file'
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Capacitor project
        run: |
          mkdir -p ios-app
          cd ios-app
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/ios

      - name: Initialize Capacitor
        working-directory: ios-app
        run: |
          cat > capacitor.config.json << 'EOF'
          {
            "appId": "com.spa.iosapp",
            "appName": "SPA iOS App",
            "webDir": "www",
            "bundledWebRuntime": false
          }
          EOF
          mkdir -p www

      - name: Decode and extract SPA
        working-directory: ios-app
        run: |
          echo "${{ inputs.spa_zip_base64 }}" | base64 --decode > spa.zip
          unzip -o spa.zip -d www/
          
          # If ZIP contains a single root folder, move contents up
          if [ $(ls -1 www | wc -l) -eq 1 ] && [ -d "www/$(ls www)" ]; then
            mv www/$(ls www)/* www/
            rmdir "www/$(ls -d www/*/ 2>/dev/null | head -1)" 2>/dev/null || true
          fi
          
          if [ ! -f www/index.html ]; then
            echo "Error: index.html not found in ZIP"
            exit 1
          fi
          
          echo "SPA contents:"
          ls -la www/

      - name: Add iOS platform
        working-directory: ios-app
        run: npx cap add ios

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install App Store Connect API Key
        run: |
          mkdir -p ~/private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8

      - name: Build iOS Archive
        working-directory: ios-app/ios/App
        run: |
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            archive \
            -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8 \
            -authenticationKeyID ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }} \
            -authenticationKeyIssuerID ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }} \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }}

      - name: Export IPA
        working-directory: ios-app/ios/App
        run: |
          cat > ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>${{ secrets.APPLE_TEAM_ID }}</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa \
            -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8 \
            -authenticationKeyID ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }} \
            -authenticationKeyIssuerID ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }} \
            -allowProvisioningUpdates

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios-app/ios/App/build/ipa/*.ipa
          retention-days: 30

      - name: Cleanup API Key
        if: always()
        run: rm -rf ~/private_keys
